##############################################################
# csv.yaml
##############################################################

# segment
# segment: "2"
# segment: "10"
segment: "20"

# height
height: "75"
# height: "95"
# height: "115"

# position
pos: "Mid" 
# pos: "Tip"

# obj
# obj: "1circle"
# obj: "2rectangle"
# obj: "3clover"
# obj: "4star"
obj: "5triangleA"